---
- name: Create Wildfly user
  user: name=wildfly shell=/bin/bash comment="Wildfly Server User"
  sudo: yes

- name: Check if current version is installed
  command: /bin/false creates="{{wildfly_installation_dir}}{{wildfly_name_complete}}"
  ignore_errors: yes
  sudo: yes
  register: check_current_version

- name: Get Wildfly
  get_url: url="{{wildfly_url}}" dest="/tmp/{{wildfly_name_complete}}.zip"
  when: check_current_version|failed

- name: Install unzip command
  apt:
    pkg: unzip
    state: present
    update_cache: yes
    cache_valid_time: 600

- name: Unarchive Wildfly
  command: /usr/bin/unzip /tmp/{{wildfly_name_complete}}.zip -d {{wildfly_installation_dir}}
  register: unarchive_wildlflay
  when: check_current_version|failed

- name: Update instalation owner
  file: path="{{wildfly_installation_dir}}{{wildfly_name_complete}}"  owner=wildfly group=wildfly state=directory
  sudo: yes


- name: Update current Wildfly sym-link
  file: src="{{wildfly_installation_dir}}{{wildfly_name_complete}}" dest={{wildfly_installation_dir}}wildfly owner=wildfly group=wildfly state=link
  sudo: yes

- name: Update Wildfly home directory so wildfly user owns file
  file: path="{{wildfly_installation_dir}}{{wildfly_name_complete}}" state=directory owner=wildfly group=wildfly recurse=yes
  sudo: yes

- name: Upload Wildfly conf file
  copy: src="wildfly.conf" dest="/etc/default/wildfly.conf" owner=root group=root mode=0644
  sudo: yes

- name: Upload Wildfly service script
  copy: src="wildfly.init.d" dest="/etc/init.d/wildfly" owner=root group=root mode=0755
  sudo: yes

- name: Add JAVA_OPTS to standadlone.conf
  lineinfile: dest={{wildfly_installation_dir}}{{wildfly_name_complete}}/bin/standalone.conf
              regexp=''
              insertafter=EOF
              line='JAVA_OPTS="$JAVA_OPTS -Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=0.0.0.0"JAVA_OPTS="$JAVA_OPTS -Djboss.bind.address=0.0.0.0 -Djboss.bind.address.management=0.0.0.0"'

- name: Restart Wildfly
  service: name=wildfly state=started enabled=yes
  sudo: yes
  register: restarted_wildfly

- name: Remove Wildfly download
  file: path="/tmp/{{wildfly_name_complete}}.zip" state=absent
  when: restarted_wildfly
